name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    env:
      VCPKG_ROOT: '${{ github.workspace }}/vcpkg'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
      # install vcpkg
    - name: Get vcpkg(windows)
      run: |
          cd ${{ github.workspace }}
          mkdir build -force
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat

    - name: Running cmake
      run: |
         cd ${{ github.workspace }}
         cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
          path: ./build
